openapi: 3.0.0
info:
  version: '0.1'
  title: ReMovie API
  description: A place to create reviews and react to them
tags: 
  - name: devices
    description: Used to create objects

paths:
  /create:
    # post:
    #   tags: 
    #     - devices
    #   summary: matches password with a service
    #   operationId: app.create_review
    #   description: Creates a new password linked to another service to the system
    #   responses:
    #     '201':
    #       description: review created
    #     '400':
    #       description: 'invalid arguments'
    #   requestBody:
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/AddReview'
    #     description: Reads item to add
    get:
      tags:
        - devices
      summary: gets new review
      operationId: app.get_review
      description: gets rating on a review once it is created
      parameters:
        - name: timestamp
          in: query
          description: limiter
          schema:
            type: string
            format: date-time
            example: 2022-01-01
      responses:
        '200':
          description: Successful review
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddReview'
        '400':
          description: bad request
          content:
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
        
  /rate:
    # post:
    #   tags: 
    #     - devices
    #   summary: allows users to rate other reviews
    #   operationId: app.rate
    #   description: creates ratings
    #   responses:
    #     '201':
    #       description: rating created
    #     '400':
    #       description: 'invalid arguments'
    #   requestBody:
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/AddRate'
    #     description: Reads item to add
    get:
      tags:
        - devices
      summary: gets new user rating
      operationId: app.get_rating
      description: gets rating on a rewview once it is created
      parameters:
        - name: timestamp
          in: query
          description: limiter
          schema:
            type: string
            format: date-time
            example: 2022-01-01
      responses:
        '200':
          description: Successful rating
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddRate'
        '400':
          description: bad request
          content:
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
  /health:
    get:
      tags:
        - devices
      summary: checks health of API
      operationId: app.get_health
      description: Checks service health
      responses:
        '200':
          description: Sucessful Health Checks
        '400':
          description: bad health request

components:
  schemas:
    AddReview:
      required: 
        - review_id
        - username
        - comment
        - rating
        - timestamp
      properties:
        review_id:
          type: string
          example: R012345
        username:
          type: string
          example: Waluigi
        comment:
          type: string
          example: This movie is good
        rating:
          type: integer
          example: 89
        timestamp:
          type: string
          format: date-time
          example: '2022-01-01'
      type: object
    
    AddRate:
      required:
        - response_id
        - user_rating
        - rate_count
        - timestamp
      properties:
        response_id:
          type: string
          example: B012345
        user_rating:
          type: boolean
          example: True
        rate_count:
          type: integer
          example: 21
        timestamp:
          type: string
          format: date-time
          example: '2022-01-01'
      type: object