pipeline {
  agent any
    stages {
      stage('Lint') {
        steps {
          sh 'pylint-fail-under --fail_under 5.0 *.py'
        }
      }
      stage('Package') { 
        steps { 
          withCredentials([string(credentialsId: 'DockerHub', variable: 'TOKEN')]) { 
          sh "docker login -u 'justtheinstinct' -p '$TOKEN' docker.io" 
          sh "docker build -t ${dockerRepoName}:latest --tag justtheinstinct/${dockerRepoName}:${imageName} ." 
          sh "docker push justtheinstinct/${dockerRepoName}:${imageName}" 
        } 
      }
      stage('Zip Artifacts') {
        steps {
          sh "zip app.zip *.py"
        }
      }

      stage('Deliver') {
        steps {
          sh "docker stop ${dockerRepoName} || true && docker rm ${dockerRepoName} || true"
          sh "docker run -d -p ${portNum}:${portNum} --name ${dockerRepoName} ${dockerRepoName}:latest"
        }
      }
      stage('Deliver') {
        steps {
          sh "docker stop ${dockerRepoName} || true && docker rm ${dockerRepoName} || true"
          sh "docker run -d -p ${portNum}:${portNum} --name ${dockerRepoName} ${dockerRepoName}:latest"
        }
      }
    }
  }
}
